### ISSUE TITLE
Add option to ddl2cpp.yml for `OverwriteAnsiString`

### ISSUE THREAD

**Issue by FelixTheC** [LASTRADA-Software/Lightweight#250]
It would be good to have the possibility to define an overwrite for the default `SqlAnsiString` type for specific tables. 

I have something like this in mind
```yaml
OverwriteAnsiString:
    - SqlWideString:
        - 'Artikel'
        -
        -
    - OtherString:
        - 'Other'
```
