### ISSUE TITLE
Better detect HasOne vs HasMany associations

### ISSUE THREAD

**Issue by christianparpart** [LASTRADA-Software/Lightweight#43]
We already detect foreign keys from A to B, so we simply need to add a back reference from B to A.

## Suggested config override:

```yaml
RelationOverrides:
    TABLE1:
        FK_COLUMN: One
    TABLE2:
        FK1: One
        FK2: Many
```

This hints ddl2cpp to use either 1:1 or 1:N relations (BelongsTo/HasOne, HasMany).
